### PR TITLE
District swing

### PR DESCRIPTION
**Pull request by JingyaoGu2**
Completed district swing feature for review

### CODE REVIEW

**Review by davebradlee — COMMENTED** [review]
This looks fine. I'm asking Terry about npx webpack. I guess it didn't compile for you without that?
Once that's done, I'll bump the version and publish to npm. Then we can have the client pick up the new version directly.
Thanks.

**Review by davebradlee — COMMENTED** [review]
Actually, 1 change request: could you make the isDistricts parameter optional, so existing code (in lambdas) will keep working until it's updated? Thanks.

**Comment by JingyaoGu2** [comment]
> This looks fine. I'm asking Terry about npx webpack. I guess it didn't compile for you without that? Once that's done, I'll bump the version and publish to npm. Then we can have the client pick up the new version directly. Thanks.

Yes. It couldn't be compiled without npx.

**Comment by JingyaoGu2** [comment]
> Actually, 1 change request: could you make the isDistricts parameter optional, so existing code (in lambdas) will keep working until it's updated? Thanks.

Doing that now.

**Pull request merged**
